#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#89B4FA"
bspc config normal_border_color "#445A7D"
bspc config active_border_color "#445A7D"
bspc config focus_follows_pointer true

bspc rule -a floorp sticky=off
bspc rule -a alacritty sticky=off

polybar &
