#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V
bspc monitor DP-1-2 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#89B4FA"
bspc config normal_border_color "#445A7D"
bspc config active_border_color "#445A7D"
bspc config focus_follows_pointer true

bspc rule -a "*" follow=off sticky=off
bspc rule -a Emacs state=tiled

polybar &
.config/emacs/bin/doom run --daemon
